Fixing a wikipedia.latestRevision() bug :
 >  page.latestRevision()
  File "/home/nico/projets/devpywiki/wikipedia.py", line 839, in latestRevision
    return int(self._permalink)
TypeError: int() argument must be a string or a number, not 'NoneType'

This was happenning when the page was not existing, because we were not raising _getexception when set by getall()

https://mediawiki.org/wiki/Special:Code/pywikipedia/5373