bug fix; AttributeError: 'tuple' object has no attribute 'major' (python 2.6 does not know named tuples)
https://mediawiki.org/wiki/Special:Code/pywikipedia/10933